/**
 * Merge the datasets, mark unknowns, emit the table and the lens scales.
 *
 * PRD.md §11 — this is the whole build-time pipeline. Nothing downstream reads
 * a TSV, and nothing downstream computes a property. The output is
 * deterministic: same inputs, byte-identical files, asserted in tests.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  AUFBAU_EXCEPTIONS,
  parseNotation,
  predict,
  sameConfiguration,
} from '../lib/elements/aufbau'
import { blockOf, groupOf, periodOf } from '../lib/elements/layout'
import { LICENCES, SOURCES } from '../lib/elements/sources'
import { tableSchema } from '../lib/elements/schema'
import {
  AUFBAU_EXCEPTION_COLOUR,
  AUFBAU_FOLLOWS_COLOUR,
  BLOCK_COLOURS,
  CATEGORY_COLOURS,
  NOT_PRODUCED_COLOUR,
  ORIGIN_COLOURS,
  RAMPS,
  TRACE_COLOUR,
  UNKNOWN_HATCH,
} from '../lib/design/palette'
import { ground } from '../lib/design/tokens'
import type { Element, PropertyValue, ProductionState, Source } from '../lib/elements/types'

const root = join(__dirname, '..')

/** The edition every figure in this build is read from. Invariant 10. */
const USGS_EDITION = 2024

function rows(path: string): string[][] {
  return readFileSync(join(root, path), 'utf8')
    .split('\n')
    .filter((line) => line.trim() && !line.startsWith('#'))
    .map((line) => line.split('\t'))
}

/** "?" is the only way the data expresses a missing value, and it lands here. */
function value(raw: string | undefined, unit: string, source: Source): PropertyValue<number> {
  if (raw === undefined || raw.trim() === '?') return { type: 'unknown' }
  const parsed = Number(raw)
  if (!Number.isFinite(parsed)) throw new Error(`not a number: ${raw}`)
  return { type: 'known', value: parsed, unit, source }
}

const configurations = new Map(
  rows('data/configurations/published.tsv').map((r) => [Number(r[0]), String(r[2])]),
)

const produced = new Map(
  rows('data/production/usgs.tsv').map((r) => [
    Number(r[0]),
    {
      commodity: String(r[2]),
      share: Number(r[3]),
      stage: String(r[4]) as 'mined' | 'refined',
      edition: Number(r[5]),
      dataYear: Number(r[6]),
      source: SOURCES.usgs,
    },
  ]),
)

const tracked = new Set(rows('data/production/tracked.tsv').map((r) => Number(r[0])))

function productionFor(z: number): ProductionState {
  const entry = produced.get(z)
  if (entry) return { type: 'produced', production: entry }
  // Invariant 9: tracked-but-absent is "not produced". Untracked is unknown —
  // USGS reports nothing about it, which is not the same as reporting nothing.
  if (tracked.has(z)) return { type: 'not-produced', edition: USGS_EDITION, source: SOURCES.usgs }
  return { type: 'unknown' }
}

const elements: Element[] = rows('data/elements/properties.tsv').map((r) => {
  const z = Number(r[0])
  const notation = configurations.get(z)
  if (!notation) throw new Error(`no published configuration for Z=${z}`)
  const subshells = parseNotation(notation)
  const anomalous = !sameConfiguration(subshells, predict(z))
  if (anomalous !== AUFBAU_EXCEPTIONS.includes(z)) {
    throw new Error(
      `Z=${z}: published configuration and the documented exception list disagree`,
    )
  }
  return {
    z,
    symbol: String(r[1]),
    name: String(r[2]),
    nameId: String(r[3]),
    mass: value(r[4], 'u', SOURCES.iupacWeights),
    category: String(r[5]) as Element['category'],
    block: blockOf(z),
    group: groupOf(z),
    period: periodOf(z),
    configuration: { notation, subshells, anomalous, source: SOURCES.nistLevels },
    origin: String(r[6]) as Element['origin'],
    discovery: value(r[7], 'year', SOURCES.discovery),
    electronegativity: value(r[8], 'Pauling', SOURCES.crc),
    atomicRadius: value(r[9], 'pm', SOURCES.slater),
    ionisationEnergy: value(r[10], 'kJ/mol', SOURCES.nistIonisation),
    meltingPoint: value(r[11], 'K', SOURCES.crc),
    density: value(r[12], 'g/cm³', SOURCES.crc),
    production: productionFor(z),
  }
})

const table = tableSchema.parse({
  generatedFrom: [
    'data/elements/properties.tsv',
    'data/configurations/published.tsv',
    'data/production/usgs.tsv',
    'data/production/tracked.tsv',
  ],
  licences: LICENCES.map((l) => ({ ...l })),
  usgsEdition: USGS_EDITION,
  elements,
})

writeFileSync(
  join(root, 'data/generated/elements.json'),
  `${JSON.stringify(table, null, 2)}\n`,
)

/**
 * Lens scales as CSS custom properties. Components name a token; they never
 * hold a hex value (CLAUDE.md conventions), and unknown gets exactly one
 * declaration for the whole product.
 */
const lines: string[] = [
  '/* GENERATED by pnpm data:build — do not edit. Source: lib/design/palette.ts */',
  ':root {',
  `  --paper: ${ground.paper};`,
  `  --ink: ${ground.ink};`,
  `  --rule: ${ground.rule};`,
  `  --muted: ${ground.muted};`,
  `  --lens-unknown: ${UNKNOWN_HATCH};`,
  `  --lens-production-id-none: ${NOT_PRODUCED_COLOUR};`,
  `  --aufbau-exception: ${AUFBAU_EXCEPTION_COLOUR};`,
  `  --trace: ${TRACE_COLOUR};`,
  `  --aufbau-follows: ${AUFBAU_FOLLOWS_COLOUR};`,
]
for (const [key, hex] of Object.entries(CATEGORY_COLOURS)) {
  lines.push(`  --lens-category-${key}: ${hex};`)
}
for (const [key, hex] of Object.entries(BLOCK_COLOURS)) {
  lines.push(`  --lens-block-${key}: ${hex};`)
}
for (const [key, hex] of Object.entries(ORIGIN_COLOURS)) {
  lines.push(`  --lens-origin-${key}: ${hex};`)
}
for (const [lens, ramp] of Object.entries(RAMPS)) {
  ramp.forEach((hex, index) => lines.push(`  --lens-${lens}-${index}: ${hex};`))
}
lines.push('}', '')

writeFileSync(join(root, 'app/generated/lens-tokens.css'), lines.join('\n'))

console.log(`data:build — ${table.elements.length} elements, ${produced.size} produced`)
